on:
  pull_request:
    paths:
      - "wba-aws-shared-infrastructure/**"

name: pull_request
jobs:
  linting_and_formatting:
    name: Linting and Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "~3.10"
          architecture: "x64"
      - name: run-ci
        working-directory: ./wba-aws-shared-infrastructure
        run: |
          pip install poetry
          poetry install
          make run-ci
